// SPDX-FileCopyrightText: 2026 Maxim Dokukin (maxdokukin.com)
// SPDX-License-Identifier: GPL-3.0-only
// xewe-os/xewe-os.ino
//
// XeWe OS firmware: XeWeCore's Os (serial console, NVS, CLI, system) plus the modules you select.
// - Project name, version, timestamp: generated by `xewe build` (xewe.lock [project]); see Config.h.
// - Your own settings and defaults: Config.h.
// - Modules: never edit src/Modules.h by hand; ./setup.sh generates it (modules live in build/modules-lib/).
// - Your own code: setup()/loop() below, after os.begin() / os.loop().

#include <XeWeCore.h>

#include "Config.h"

// The Os comes first: modules register themselves with it from their constructors.
XeWeOs os({
    .project_name    = PROJECT_NAME,
    .version         = BUILD_VERSION,
    .build_timestamp = BUILD_TIMESTAMP,
    .url             = PROJECT_URL,
    .serial          = {.baud_rate = SERIAL_BAUD_RATE},
});

// Generated by ./setup.sh: includes and declares the selected modules, in dependency order.
#if __has_include("src/Modules.h")
#include "src/Modules.h"
#endif

void setup() {
    os.begin();
}

void loop() {
    os.loop();
}
