// SPDX-FileCopyrightText: 2026 Maxim Dokukin (maxdokukin.com)
// SPDX-License-Identifier: GPL-3.0-only
// xewe-os/xewe-os.ino
//
// XeWe OS firmware: XeWeCore's Os (serial console, NVS, CLI, system) plus the modules you select.
// - Project name, version, timestamp: generated by `xewe build` (xewe.toml [project]); see Config.h.
// - Your own settings and defaults: Config.h.
// - Modules: never edit src/Modules.h by hand; ./setup.sh generates it (modules live in build/modules/).
// - Your own code: setup()/loop() below, after os.begin() / os.loop().
// - Your own module: src/YourModule/ (minimal) or src/YourModuleFull/ (every hook; project-local,
//   setup never touches them).

#include <XeWeCore.h>

#include "Config.h"

// The Os comes first: modules register themselves with it from their constructors.
XeWeOs os({
    .project_name    = PROJECT_NAME,
    .version         = BUILD_VERSION,
    .build_timestamp = BUILD_TIMESTAMP,
    .url             = PROJECT_URL,
    .serial          = {.baud_rate = SERIAL_BAUD_RATE},
});

// Generated by ./setup.sh: includes and declares the selected modules, in dependency order.
#if __has_include("src/Modules.h")
#include "src/Modules.h"
#endif

// Project-local modules are declared here, after the generated ones, in dependency order.
// src/YourModule/ is an example: rename it, or delete the folder and these two lines.
#include "src/YourModule/YourModule.h"
YourModule your_module(os);

// src/YourModuleFull/ is the full tour of xewe::Module (every hook, commented; id your_mod_full):
// copy what you need, delete what you do not need (or the folder, these lines and the
// listeners.add() call in setup()).
#include "src/YourModuleFull/YourModuleFull.h"
YourModuleFull your_module_full(os);

// A listener: the sketch reacts to a module without the module knowing the sketch.
struct SketchLevelListener : LevelListener {
    void on_level(uint16_t level, const void*) override { os.serial.printf("sketch: level is now %u", level); }
} sketch_level_listener;

void setup() {
    your_module_full.listeners.add(&sketch_level_listener);
    os.begin();
}

void loop() {
    os.loop();
}
